# Generated by Django 3.1.3 on 2021-01-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
