# Generated by Django 3.1.3 on 2021-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210116_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(choices=[('Noticias', 'Noticias'), ('Trading', 'Trading'), ('DeFi', 'DeFi'), ('Blockchain', 'Blockchain'), ('Degen', 'Degen')], default='Noticias', max_length=20),
        ),
    ]
