# Generated by Django 3.1.3 on 2021-01-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
