# Generated by Django 3.1.3 on 2021-01-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210116_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicar')], default=0),
        ),
    ]
