# Generated by Django 3.1.3 on 2021-01-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210116_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
