# Generated by Django 3.1.3 on 2021-01-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210117_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(default='https://coinsmos.s3.us-east-2.amazonaws.com/coinastrologo.png', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('noticias', 'noticias'), ('trading', 'trading'), ('blockchain', 'blockchain'), ('defi', 'defi'), ('degen', 'degen')], default='Noticias', max_length=20),
        ),
    ]
