# Generated by Django 3.1.3 on 2021-01-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentario',
        ),
    ]
