# Generated by Django 3.1.3 on 2021-01-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210119_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
