# Generated by Django 3.1.3 on 2021-01-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210119_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDestacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', models.CharField(max_length=10000)),
            ],
        ),
    ]
