# Generated by Django 3.1.3 on 2021-01-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_postdestacado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdestacado',
            old_name='Banner',
            new_name='banner',
        ),
    ]
