# Generated by Django 3.1.3 on 2021-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210119_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdestacado',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='postdestacado',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postdestacado',
            name='status',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicacion')], default=0),
        ),
    ]
