# Generated by Django 3.1.3 on 2021-01-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210119_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDestacado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read',
        ),
    ]
