# Generated by Django 3.1.3 on 2021-01-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210119_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.IntegerField(choices=[(0, 'Estandar'), (1, 'Destacado 1 (Principal)'), (2, 'Destacado 2'), (3, 'Destacado 3'), (4, 'Destacado 4')], default=0),
        ),
    ]
