# Generated by Django 3.1.3 on 2021-01-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210120_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='name',
        ),
    ]
