# Generated by Django 3.1.3 on 2021-01-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210120_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='comment',
        ),
    ]
