# Generated by Django 3.1.3 on 2021-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210120_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.CharField(default='https://i.ibb.co/5FqNvJP/banner3.png', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='destacado',
            field=models.IntegerField(choices=[(0, 'Estandar'), (1, 'Destacado')], default=0),
        ),
    ]
